# Generated by Django 5.1.5 on 2025-04-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.DecimalField(decimal_places=0, max_digits=10)),
                ('desc', models.TextField()),
                ('loca', models.IntegerField()),
            ],
        ),
    ]
